server:
  port: 90
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期

# 公钥和私钥信息
vinspier:
  jwt:
    secret: vinspier@Login(Auth}*^31)&heiMa% # 登录校验的密文
    pubKeyPath: C:\\tmp\\rsa\\rsa.pub # 公钥地址
    priKeyPath: C:\\tmp\\rsa\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: access_token # token存在cookie中的key
    cookieMaxAge: 60 # cookie失效时间