server:
  port: 88
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shoppinig
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#  redis:
#    host: 192.168.248.129
  rabbitmq:
    virtual-host: /vinspier
    host: 127.0.0.1
    username: vinspier
    password: vinspier
    template:
      exchange: vinspier.sms.exchange # 缺省的交换机名称 发送消息如果不指定交换机就会使用这个
    publisher-confirms: true # 生产者确认机制，确保消息会正确发送，如果发送失败会有错误回执，从而触发重试
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.vinspier.user.pojo