server:
  port: 87
spring:
  application:
    name: goods-web
  thymeleaf:
      cache: false
  main:
    allow-bean-definition-overriding: true
  # 消息中间件rabbitMQ
  rabbitmq:
      host: 127.0.0.1
      username: vinspier
      password: vinspier
      virtual-host: /vinspier
      template:
        exchange: vinspier.item.exchange # 缺省的交换机名称 发送消息如果不指定交换机就会使用这个
      publisher-confirms: true # 生产者确认机制，确保消息会正确发送，如果发送失败会有错误回执，从而触发重试
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
