server:
  port: 89
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 127.0.0.1
    virtual-host: /vinspier
    username: vinspier
    password: vinspier

# ============================= 定义常量开始 =======================================
vinspier:
  sms:
    accessKeyId: LTAI3dQhZLeO4RWH # accessKeyId
    accessKeySecret: gAsEKsXakv9Ysp2T7lPvawEmbmhNbT # AccessKeySecret
    signName: vinspier # 签名名称
    verifyCodeTemplate: SMS_165418038 # 模板名称